name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: make docker-build
    - name: Run tests
      run: make docker-runtest-all
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
    # A list of files, directories, and wildcard patterns to cache and restore
      path: 
    # An explicit key for restoring and saving the cache
      key: 
    # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
      restore-keys: # optional
    # The chunk size used to split up large files during upload, in bytes
      upload-chunk-size: # optional
